title:  THINK FREE
description: 골빈해커의 생각의 파편들

url: http://golbin.github.io
baseurl: ""
paginate_path: "post/page/:num/"
permalink: post/:year/:month/:title/

markdown: kramdown
highlighter: rouge
gems:
 - jekyll-paginate
 - jekyll-gist
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: golbin 
   twitter: golbin
   facebook: hacker.golbin
   email: golbin@gmail.com
